version: '3.7'
services:
  backend-api:
    container_name: backend-api
    build: ./backend_api/simple-api
    networks:
      - tp1-network
    ports:
      - "8090:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    build: ./postgres
    networks:
      - tp1-network
    ports:
      - "8081:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/datadir:/var/lib/postgresql/data
  httpd:
    build: ./httpd
    container_name: httpd
    ports:
      - "80:80"
    networks:
      - tp1-network
    depends_on:
      - backend-api
networks:
  tp1-network:
    driver: bridge